# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Dev\neyroNet\code\NNCopyVsCode\NNGUI\uixml\helpQueryDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_helpQueryDialog(object):
    def setupUi(self, helpQueryDialog):
        helpQueryDialog.setObjectName("helpQueryDialog")
        helpQueryDialog.resize(663, 201)
        self.textGroupBox = QtWidgets.QGroupBox(helpQueryDialog)
        self.textGroupBox.setGeometry(QtCore.QRect(10, 30, 641, 161))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textGroupBox.setFont(font)
        self.textGroupBox.setObjectName("textGroupBox")
        self.label = QtWidgets.QLabel(self.textGroupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 621, 501))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")

        self.retranslateUi(helpQueryDialog)
        QtCore.QMetaObject.connectSlotsByName(helpQueryDialog)

    def retranslateUi(self, helpQueryDialog):
        _translate = QtCore.QCoreApplication.translate
        helpQueryDialog.setWindowTitle(_translate("helpQueryDialog", "Помощь"))
        self.textGroupBox.setTitle(_translate("helpQueryDialog", "Опрос"))
        self.label.setText(_translate("helpQueryDialog", "В разделе \"Опрос\" проводится опрос нейросети.\n"
"Введите параметры в слоты \"Входные значения\" и нажмите кнопку \"Опрос\".\n"
"В окне результат опроса появится значение.\n"
"При проведении опроса сети без тренировки (или загруженных весов) результат\n"
"опроса непредсказуем, т.к. веса для сети генерируются случайным образрм\n"
"при каждом запуске программы."))
