# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Dev\neyroNet\code\NNCopyVsCode\NNGUI\uixml\MBDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_messageDBox(object):
    def setupUi(self, messageDBox):
        messageDBox.setObjectName("messageDBox")
        messageDBox.resize(370, 150)
        self.gridLayout_2 = QtWidgets.QGridLayout(messageDBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.iconLabel = QtWidgets.QLabel(messageDBox)
        self.iconLabel.setMaximumSize(QtCore.QSize(50, 50))
        self.iconLabel.setObjectName("iconLabel")
        self.gridLayout.addWidget(self.iconLabel, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(messageDBox)
        self.label.setMaximumSize(QtCore.QSize(50, 10))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(messageDBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.messageLabel = QtWidgets.QLabel(messageDBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.messageLabel.setFont(font)
        self.messageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout.addWidget(self.messageLabel, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(messageDBox)
        QtCore.QMetaObject.connectSlotsByName(messageDBox)

    def retranslateUi(self, messageDBox):
        _translate = QtCore.QCoreApplication.translate
        messageDBox.setWindowTitle(_translate("messageDBox", "Dialog"))
        self.iconLabel.setText(_translate("messageDBox", "iconLabel"))
        self.messageLabel.setText(_translate("messageDBox", "messageLabel"))
