# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Dev\neyroNet\code\NNCopyVsCode\NNGUI\startWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 544)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("f:\\Dev\\neyroNet\\code\\NNCopyVsCode\\NNGUI\\resources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogoLabel.setGeometry(QtCore.QRect(-10, 0, 541, 191))
        self.LogoLabel.setText("")
        self.LogoLabel.setPixmap(QtGui.QPixmap("f:\\Dev\\neyroNet\\code\\NNCopyVsCode\\NNGUI\\../../../logo.png"))
        self.LogoLabel.setScaledContents(False)
        self.LogoLabel.setWordWrap(False)
        self.LogoLabel.setObjectName("LogoLabel")
        self.StartWorkBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StartWorkBtn.setGeometry(QtCore.QRect(10, 460, 111, 41))
        self.StartWorkBtn.setAutoDefault(False)
        self.StartWorkBtn.setDefault(False)
        self.StartWorkBtn.setFlat(False)
        self.StartWorkBtn.setObjectName("StartWorkBtn")
        self.MainTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.MainTextLabel.setGeometry(QtCore.QRect(240, 190, 381, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.MainTextLabel.setFont(font)
        self.MainTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MainTextLabel.setObjectName("MainTextLabel")
        self.DevLabel = QtWidgets.QLabel(self.centralwidget)
        self.DevLabel.setGeometry(QtCore.QRect(550, 350, 291, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DevLabel.setFont(font)
        self.DevLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.DevLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.DevLabel.setObjectName("DevLabel")
        self.FAQBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FAQBtn.setGeometry(QtCore.QRect(140, 460, 111, 41))
        self.FAQBtn.setAutoDefault(False)
        self.FAQBtn.setDefault(False)
        self.FAQBtn.setFlat(False)
        self.FAQBtn.setObjectName("FAQBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "УГЛТУ"))
        self.StartWorkBtn.setText(_translate("MainWindow", "Начать работу"))
        self.MainTextLabel.setText(_translate("MainWindow", "Нейронная сеть"))
        self.DevLabel.setText(_translate("MainWindow", "\n"
"\n"
"Руководитель проекта: Побединских В.В.\n"
"\n"
"\n"
"Разработал:                     Писарев И.Д."))
        self.FAQBtn.setText(_translate("MainWindow", "О программе"))
